const Router=require("express").Router()
const MaincategoryRouter=require("./MaincategoryRouter")
const SubcategoryRouter=require("./SubcategoryRouter")
const BrandRouter=require("./BrandRouter")
const FeatureRouter=require("./FeatureRouter")
const FaqRouter=require("./FaqRouter")
const SettingRouter=require("./SettingRouter")
const ProductRouter=require("./ProductRouter")
const UserRouter=require("./UserRouter")
const CartRouter=require("./CartRouter")
const WishlistRouter=require("./WishlistRouter")
const CheckoutRouter=require("./CheckoutRouter")
const NewsLetterRouter=require("./NewsLetterRouter")
const ContactUsRouter=require("./ContactUsRouter")
const TestimonialRouter=require("./TestimonialRouter")


Router.use("/maincategory",MaincategoryRouter)
Router.use("/subcategory",SubcategoryRouter)
Router.use("/brand",BrandRouter)
Router.use("/features",FeatureRouter)
Router.use("/faq",FaqRouter)
Router.use("/setting",SettingRouter)
Router.use("/product",ProductRouter)
Router.use("/user",UserRouter)
Router.use("/wishlist",WishlistRouter)
Router.use("/checkout",CheckoutRouter)
Router.use("/newsletter",NewsLetterRouter)
Router.use("/contactUs",ContactUsRouter)
Router.use("/testimonial",TestimonialRouter)
Router.use("/cart",CartRouter)


module.exports=Router